### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by chosa91** [basememara/ThemeKit#1]
Every time you change the theme it'll increase the memory usage :/ 
As you mentioned in the post it'll be good for cases where theme switching happens rarely.

**Comment by basememara** [comment]
Is this because memory isn't completely deallocated when removing/adding controls to the window? I wonder if there's a way around this since there's not much to this:
```
UIApplication.shared.windows.forEach { window in
    window.subviews.forEach { view in
        view.removeFromSuperview()
        window.addSubview(view)
    }
}
```

**Comment by chosa91** [comment]
Yes, I've seen the solution in the source code. I'm just thinking...
But if you will, you could close this issue.
